version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /templates/fumadocs
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
